import os
import streamlit as st
import joblib
import warnings
import nltk
import numpy as np
from scipy.sparse import hstack

warnings.filterwarnings("ignore")

# Setup NLTK gracefully mapped to Streamlit cache
@st.cache_resource
def setup_nltk():
    for req in ['punkt', 'stopwords', 'punkt_tab']:
        nltk.download(req, quiet=True)

setup_nltk()

from nlp_utils import clean_text, get_handcrafted_features

# Use absolute paths for stability in Streamlit Cloud
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "model.pkl")
VECTORIZER_PATH = os.path.join(BASE_DIR, "vectorizer.pkl")
SCALER_PATH = os.path.join(BASE_DIR, "scaler.pkl")
DATASET_PATH = os.path.join(BASE_DIR, "dataset.csv")

def ensure_dependencies():
    """Ensure dataset and models exist; if not, generate and train."""
    # Check if necessary model objects exist
    if not (os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH) and os.path.exists(SCALER_PATH)):
        with st.spinner("Model missing! Auto-training model... Please wait..."):
            cwd = os.getcwd()
            os.chdir(BASE_DIR)
            
            # Auto-regenerate dataset if missing
            if not os.path.exists(DATASET_PATH):
                from generate_dataset import main as gen_data
                st.info("Dataset missing! Generating dataset...")
                gen_data()
            
            # Auto-train models
            from train import main as train_model
            train_model()
            
            os.chdir(cwd)

@st.cache_resource
def load_objects():
    ensure_dependencies()
    try:
        model = joblib.load(MODEL_PATH)
        vectorizer = joblib.load(VECTORIZER_PATH)
        scaler = joblib.load(SCALER_PATH)
        return model, vectorizer, scaler
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return None, None, None

def main():
    st.set_page_config(page_title="AI vs Human Text Detector", page_icon="🤖", layout="centered")
    
    st.title("AI vs Human Text Detector")
    st.markdown("Analyze text to determine if it was written by a human or generated by an AI model.")
    st.markdown("---")
    
    model, vectorizer, scaler = load_objects()
    
    if model and vectorizer and scaler:
        user_text = st.text_area(
            label="Input Text", 
            height=200, 
            placeholder="Paste your text here...",
            label_visibility="collapsed"
        )
        
        if st.button("Analyze"):
            if not user_text.strip():
                st.warning("Please enter some text to classify.")
                return

            with st.spinner("Analyzing..."):
                # Preprocess and Extract Features
                cleaned = clean_text(user_text)
                hc_features = get_handcrafted_features([user_text])
                hc_scaled = scaler.transform(hc_features)
                tfidf_features = vectorizer.transform([cleaned])
                combined_features = hstack([tfidf_features, hc_scaled])
                
                # Predict
                prediction = model.predict(combined_features)[0]
                probabilities = model.predict_proba(combined_features)[0]
                
                human_prob = probabilities[0] * 100
                ai_prob = probabilities[1] * 100
                
                label = "AI-generated" if prediction == 1 else "Human-written"
                confidence = probabilities[prediction] * 100

                # --- EXPLAINABILITY LOGIC ---
                # Retrieve feature names
                tfidf_names = vectorizer.get_feature_names_out()
                hc_names = ['Sentence Length Variance', 'Punctuation Frequency', 'Capitalization Ratio', 'Word Repetition Ratio']
                feature_names = np.concatenate([tfidf_names, hc_names])
                
                # Calculate exact feature contributions (Score = Weight * Input Value)
                instance_features = combined_features.toarray()[0]
                contributions = model.coef_[0] * instance_features
                
                # Sort indices of contributions
                sorted_indices = np.argsort(contributions)
                
                # Top positive contributions push toward Class 1 (AI)
                top_ai_idx = sorted_indices[-5:][::-1] 
                
                # Top negative contributions push toward Class 0 (Human)
                top_human_idx = sorted_indices[:5]
                
                # Filter out ones with zero contribution
                ai_reasons = [(feature_names[i], contributions[i]) for i in top_ai_idx if contributions[i] > 0]
                human_reasons = [(feature_names[i], contributions[i]) for i in top_human_idx if contributions[i] < 0]

            # UI Update
            st.markdown("---")
            if label == "AI-generated":
                st.error(f"**Result: {label}**")
            else:
                st.success(f"**Result: {label}**")
                
            st.write(f"**Confidence:** {confidence:.1f}%")
            
            st.markdown("### Breakdown")
            st.progress(float(probabilities[1]), text=f"AI Probability: {ai_prob:.1f}%")
            st.progress(float(probabilities[0]), text=f"Human Probability: {human_prob:.1f}%")
            
            # --- EXPLAINER UI ---
            st.markdown("---")
            with st.expander("🔍 Why did the model choose this?"):
                st.write("The model identified the following key patterns and words that heavily influenced its decision:")
                
                col1, col2 = st.columns(2)
                with col1:
                    st.markdown("**Triggers for 'AI-generated':**")
                    if not ai_reasons:
                        st.caption("*(None)*")
                    else:
                        for feat, score in ai_reasons:
                            st.write(f"- **{feat}**")
                            # st.caption(f"Impact: {score:.2f}")
                            
                with col2:
                    st.markdown("**Triggers for 'Human-written':**")
                    if not human_reasons:
                        st.caption("*(None)*")
                    else:
                        for feat, score in human_reasons:
                            st.write(f"- **{feat}**")
                            # st.caption(f"Impact: {score:.2f}")

if __name__ == "__main__":
    main()
