import os
import streamlit as st
import joblib
import warnings
import nltk
from scipy.sparse import hstack

warnings.filterwarnings("ignore")

# Setup NLTK gracefully mapped to Streamlit cache
@st.cache_resource
def setup_nltk():
    for req in ['punkt', 'stopwords', 'punkt_tab']:
        nltk.download(req, quiet=True)

setup_nltk()

from nlp_utils import clean_text
from features import extract_features

# Use absolute paths for stability in Streamlit Cloud
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "model.pkl")
VECTORIZER_PATH = os.path.join(BASE_DIR, "vectorizer.pkl")
SCALER_PATH = os.path.join(BASE_DIR, "scaler.pkl")
DATASET_PATH = os.path.join(BASE_DIR, "dataset.csv")

def ensure_dependencies():
    """Ensure dataset and models exist; if not, generate and train."""
    # Check if necessary model objects exist
    if not (os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH) and os.path.exists(SCALER_PATH)):
        with st.spinner("Model missing! Auto-training model... Please wait..."):
            cwd = os.getcwd()
            os.chdir(BASE_DIR)
            
            # Auto-regenerate dataset if missing
            if not os.path.exists(DATASET_PATH):
                from generate_dataset import main as gen_data
                st.info("Dataset missing! Generating dataset...")
                gen_data()
            
            # Auto-train models
            from train import main as train_model
            train_model()
            
            os.chdir(cwd)

@st.cache_resource
def load_objects():
    ensure_dependencies()
    try:
        model = joblib.load(MODEL_PATH)
        vectorizer = joblib.load(VECTORIZER_PATH)
        scaler = joblib.load(SCALER_PATH)
        return model, vectorizer, scaler
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return None, None, None

def explain_prediction(text, prediction):
    """Provides a simple, user-friendly explanation based on the prediction."""
    if prediction == 1:
        return "The text exhibits highly structured writing, formal tone, and structural consistency typical of AI generation."
    else:
        return "The text shows natural irregularities, casual phrasing, slang, or emotional tone typically found in human writing."

def main():
    st.set_page_config(page_title="AI vs Human Text Detector", page_icon="🤖", layout="centered")
    
    st.title("AI vs Human Text Detector")
    st.markdown("Analyze text to determine if it was written by a human or generated by an AI model.")
    st.markdown("---")
    
    model, vectorizer, scaler = load_objects()
    
    if model and vectorizer and scaler:
        user_text = st.text_area(
            label="Input Text", 
            height=200, 
            placeholder="Paste your text here...",
            label_visibility="collapsed"
        )
        
        if st.button("Analyze"):
            if not user_text.strip():
                st.warning("Please enter some text to classify.")
                return

            with st.spinner("Analyzing..."):
                # Preprocess and Extract Features
                cleaned = clean_text(user_text)
                hc_features = [extract_features(user_text)]
                
                print(f"Debug: len(hc_features[0]) = {len(hc_features[0])}")
                print(f"Debug: scaler.n_features_in_ = {scaler.n_features_in_}")
                st.write(f"**Debug info:** Scaler expects: {scaler.n_features_in_} features.")
                
                if len(hc_features[0]) != scaler.n_features_in_:
                    st.error(f"Feature mismatch! Extracted {len(hc_features[0])} features, but model expects {scaler.n_features_in_}.")
                    return

                hc_scaled = scaler.transform(hc_features)
                tfidf_features = vectorizer.transform([cleaned])
                combined_features = hstack([tfidf_features, hc_scaled])
                
                # Predict
                prediction = model.predict(combined_features)[0]
                probabilities = model.predict_proba(combined_features)[0]
                
                # --- POST-PREDICTION HEURISTICS ---
                # Retrieve raw feature array [sent_var, punct, cap, rep, inconsist, num, slang]
                feat_array = hc_features[0]
                sent_var = feat_array[0]
                inconsistency = feat_array[4]
                slang_ratio = feat_array[6]
                
                if prediction == 1 and (inconsistency >= 1 or slang_ratio > 0):
                    # AI predicted, but high grammar inconsistency and slang -> Adjust to Human
                    prediction = 0
                    probabilities[0] = min(0.85, probabilities[0] + 0.4)
                    probabilities[1] = 1.0 - probabilities[0]
                elif prediction == 0 and slang_ratio == 0 and inconsistency == 0 and sent_var < 2.0:
                    # Human predicted, but incredibly structured and zero slang -> Adjust to AI
                    prediction = 1
                    probabilities[1] = min(0.85, probabilities[1] + 0.4)
                    probabilities[0] = 1.0 - probabilities[1]
                
                human_prob = probabilities[0] * 100
                ai_prob = probabilities[1] * 100
                
                label = "AI-generated" if prediction == 1 else "Human-written"
                confidence = probabilities[prediction] * 100

            # UI Update
            st.markdown("---")
            if label == "AI-generated":
                st.error(f"**Result: {label}**")
            else:
                st.success(f"**Result: {label}**")
                
            st.write(f"**Confidence:** {confidence:.1f}%")
            
            st.markdown("### Breakdown")
            st.progress(float(probabilities[1]), text=f"AI Probability: {ai_prob:.1f}%")
            st.progress(float(probabilities[0]), text=f"Human Probability: {human_prob:.1f}%")
            
            # Simple, human-readable Explanations
            st.markdown("---")
            st.info(f"**Why this result:** {explain_prediction(user_text, prediction)}")

if __name__ == "__main__":
    main()
